Repository mattermost/mattermost-app-test, pull requests merged in 2022-03, with the labels that each got.

#13 [MM-40653] Update to latest version of apps plugin
  go.mod
  go.sum
  http.go
Labels: 4: Reviews Complete

#15 Various fixes for test app
  command.go
  embedded.go
  go.mod
  go.sum
  http.go
  main.go
  subscriptions.go
Labels: 3: QA Review

#16 MM-42640: include text with HTTP 500
  error.go
Labels: 2: Dev Review, 3: QA Review

#17 MM-42637: fixed `/test embedded create` command
  embedded.go
  manifest.json
Labels: 4: Reviews Complete
